export default {
  ORANGE_COLOR: '#FF851B',
  LIME_COLOR: '#00FF00',
  GREEN_COLOR: '#008080',
  WHITE_COLOR: '#ffffff',
  GREY_COLOR: '#666',
  BORDER_RADIUS_MINI: 5,
  BORDER_RADIUS_SMALL: 20,
  BORDER_RADIUS_MEDIUM: 40,
  FONT_SIZE_SMALL: 20,
  FONT_SIZE_MEDIUM: 40,
  FONT_SIZE_LARGE: 90,
  MARGIN_SIZE_SMALL: 20,
  PADDING_SIZE: 10
};
